[workspace]
members = [
    "jupiter-swap-api-client",
    "example",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "=1.18.23"
solana-client = "=1.18.23"
solana-account-decoder = "=1.18.23"
